Fix test suite
Accessing members on boolean objects cannot work, this was an oversight
introduced in version 0.2.1 causing errors like

```
        else:
            reply = await coro
>           assert (reply == expected_reply).all()
E           AttributeError: 'bool' object has no attribute 'all'
```